### ISSUE TITLE
Get climate status

### ISSUE THREAD

**Issue by stgraber** [joeshaw/leaf#1]
Hey there,

Thanks for the great work!
The integration I've been using in home-assistant for a while recently broke so I've now switched over to using this Go package to build a basic daemon that pushes the data over MQTT as well as support triggering the climate control over it.

The main thing I'm missing is a boolean for whether the climate control is active or not.
This is something I used to have in the other implementation so presumably that should be available somewhere in the API.

I don't know if this is a currently missing field coming as part of the info/battery data or if this would need a separate API call just to retrieve it, but given that climate control turns itself off after 15min or if the car is started, it'd be good to be able to get that state so I can render a proper on/off switch for it.

**Comment by joeshaw** [comment]
Thanks for reaching out, I hope the library works out for you. Unfortunately this API does not expose whether the climate control is active or not, which is a big regression from the old API. 

With my own HomeKit implementation I have to just keep the active state off and treat the button as just turning climate control on. It's definitely not as nice as having it be a toggle, but it's the best we can do.

**Comment by stgraber** [comment]
That's unfortunate, kinda hoping they actually get someone to design a proper API at some point...
This one looks less awful than some of the previous ones but they still keep missing the basics.

By the way, I noticed the API exposes the cabin temperature in degrees Celsius, it'd be neat if the Go package could support it too, though I'm unsure how you'd do that cleanly without an API break :(

The patch I applied locally looks like:
```diff
diff --git a/session.go b/session.go
index 01d1ad8..2718403 100644
--- a/session.go
+++ b/session.go
@@ -252,6 +252,10 @@ type BatteryRecords struct {
        TimeRequired200_6kW TimeRequired `json:"timeRequired200_6kW"`
 }
 
+type TemperatureRecords struct {
+       Temperature string `json:"inc_temp"`
+}
+
 type VehicleInfo struct {
        VIN       string `json:"uvi"`
        ModelName string `json:"modelname"`
@@ -328,26 +332,27 @@ func (s *Session) Login() (*VehicleInfo, *BatteryRecords, error) {
        return &vehicle.VehicleInfo, &vehicle.BatteryRecords, nil
 }
 
-func (s *Session) BatteryStatus() (*BatteryRecords, error) {
+func (s *Session) BatteryStatus() (*BatteryRecords, *TemperatureRecords, error) {
        resp, err := s.doRetryAuth(
                "GET",
                fmt.Sprintf("/battery/vehicles/%s/getChargingStatusRequest", s.data.VIN),
                nil,
        )
        if err != nil {
-               return nil, err
+               return nil, nil, err
        }
        defer resp.Body.Close()
 
        var respBody struct {
                BatteryRecords BatteryRecords `json:"batteryRecords"`
+               TemperatureRecords TemperatureRecords `json:"temperatureRecords"`
        }
 
        if err := json.NewDecoder(resp.Body).Decode(&respBody); err != nil {
-               return nil, err
+               return nil, nil, err
        }
 
-       return &respBody.BatteryRecords, nil
+       return &respBody.BatteryRecords, &respBody.TemperatureRecords, nil
 }
 
 type commonResponse struct {
```

**Comment by joeshaw** [comment]
There's not yet any API stability, so I'd be happy to take that patch if you want to submit a PR for it.

I assume the answer is no, but is there any way to use that information to infer whether the climate control is activated?

**Comment by stgraber** [comment]
Not really, you can definitely see the temperature increasing when climate control is on, but it can also just as well be that the car is in the sun now...

What I've done on my side for now is keep an internal state for the climate control.
Basically when asked to turn it on, I record it as on, then start a 15min timer and mark it as off at the end of the 15min.
With one exception, if the car reports it's charging, then I ignore the timer and mark it as off once the car is unplugged.

I believe that replicates what the internal car logic does, at least on my 2019 Leaf. Feels very dumb of them not to report the climate status...

**Comment by joeshaw** [comment]
I agree.  I was stunned when it wasn't in the reverse engineered documentation, and then I opened the app and found that it doesn't report it either.  (So it's _possible_ there is an API, but it's just not used in the app and thus hidden from us.)

I think there is a timer for the car even when it's plugged in.  I think it might be 2 hours.

Your heuristic makes a lot of sense, I may use it in my Homekit implementation (https://github.com/joeshaw/leaf-homekit)

**Comment by joeshaw** [comment]
FYI, my Leaf (US 2017) does not have a `temperatureRecords` field.  There is an `interiorTempRecords` field but it's `null`.

**Comment by stgraber** [comment]
Let's close this as there isn't really anything to be done at this point but keep an eye on the API and see if they add the information somewhere.
